### PR TITLE
suggest testthat 3.0.0; tidy up description

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Hmm, I am not sure why bumping the `testthat` version leads tests to fail 🤔

**Comment by ianmcook** [comment]
Thanks! Here's the test that's failing: [edit: oops, no, this is a red herring]
```r
test_that("query() fails on two very long expressions with no aliases", {
  expect_error(
    query("SELECT 1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1, 1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+2 FROM games"),
    "alias"
  )
})
```
This relates to #1.

**Comment by ianmcook** [comment]
When parallel testing is enabled, the test data loaded in `setup-load_data.R` does not get loaded into the workers, so all the tests are skipped. The tests all finish so quickly that I'm not sure there's much benefit in enabling parallel testing. Maybe disable that for now?

**Comment by IndrajeetPatil** [comment]
Fascinating!

Okay, turning it off.

**Pull request merged**
